### PR TITLE
update pytest config

### LINKED ISSUE #4619: Configure pytest to display the logs by default
When a developer runs the tests, the logs of the server are not shown by default. For this it's required to add the option: `--log-cli-level=DEBUG`. I think it would make sense to adjust the pytest configuration file to show the logs by default.

This can be done by setting the following in the pyproject.toml file:

```
 [tool.pytest.ini_options]
addopts = "--log-cli-level=DEBUG"
```

### PR DESCRIPTION
**Pull request by wouterdb**
# Description

to always display logs

it doesn't make the output prettier, but it does make it more informative

closes #4619 

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [x] Attached issue to pull request
- [x] Changelog entry

### CODE REVIEW

**Comment by bartv** [comment]
I remember that we discussed this once during a meeting / retro and there was reason not to do this iirc. I rarely need to use these logs for debugging so better to ask the team @sanderr @arnaudsjs @Hugo-Inmanta

**Comment by arnaudsjs** [comment]
> I remember that we discussed this once during a meeting / retro and there was reason not to do this iirc. I rarely need to use these logs for debugging so better to ask the team @sanderr @arnaudsjs @Hugo-Inmanta

I don't see an issue with this.

**Comment by sanderr** [comment]
Me neither, and I don't recall the conclusion that we wouldn't.

**Review by FloLey — APPROVED** [review]

**Comment by wouterdb** [comment]
https://github.com/pytest-dev/pytest/issues/10553

**Review by FloLey — APPROVED** [review]

**Pull request closed without merging**
