### PR TITLE
Ensure the Inmanta OSS product version is reported correctly

### LINKED ISSUE #2622: OSS product version reported incorrectly
**Problem:**

Inmanta OSS reports the version of the `inmanta-core` package as the product version while it should report the version of the `inmanta` package See: https://github.com/inmanta/inmanta-core/blob/625947ed62093b87f9932ff9ec9c7dc0f20eded1/src/inmanta/server/extensions.py#L133

**Tasks:**

- [ ] Fix the issue on the master branch
- [ ] Cherry-pick the fix on the iso4 branch

### PR DESCRIPTION
**Pull request by arnaudsjs**
# Description

Ensure the Inmanta OSS product version is reported correctly

closes #2622 

# Self Check:

- [x] Attached issue to pull request
- [x] Changelog entry
- [x] Type annotations are present
- [x] Code is clear and sufficiently documented
- [x] No (preventable) type errors (check using make mypy or make mypy-diff)
- [x] Sufficient test cases (reproduces the bug/tests the requested feature)
- [x] Correct, in line with design
- [ ] ~~End user documentation is included or an issue is created for end-user documentation~~

# Reviewer Checklist:

- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Code is clear and sufficiently documented
- [ ] Correct, in line with design

### CODE REVIEW

**Review by andraskvr — APPROVED** [review]

**Review by sanderr — COMMENTED** [review]
Is this a sensible approach? This way `inmanta-core` is no longer a stand-alone package. It will require the `inmanta` package to be installed as well, which only exists for backwards compatibility as far as I know. That is, unless we plan to use `inmanta` as the OSS product package, but even in that case this will not work for ISO. How does ISO currently handle this? Could we do something similar for `inmanta`?

**Comment by arnaudsjs** [comment]
True. Note, that the inmanta package is actually a product package. The only reason why it's not called inmanta-oss is because we didn't have the time to update all the reference to the inmanta package to inmanta-oss. But indeed, there is a dependency between inmanta-core and inmanta. For ISO this doesn't cause an issue because it uses the LicensedFeatureManager instead of the FeatureManager. @bartv What is your opinion on this?

**Comment by bartv** [comment]
I think we have to treat inmanta-oss as a full product package. Where is the version used? I guess only for --version and the status in the dashboard?

**Comment by arnaudsjs** [comment]
It's used on:

* in the `--version` command
* status on the dashboard
* Version in openapi documentation

**Comment by bartv** [comment]
Those should all be the product version imho and not core. In the oss version there is of course not a license file to get the version packages from.

I think / fear that the best solution is to "brute" force it a bit. Something like:
```python
packages = ["inmanta-oss", "inmanta", "inmanta-core"]
version = None
for package in packages:
    try:
        version = pkg_resources.get_distribution(package).version
    except pkg_resources.DistributionNotFound:
        pass

if version is None:
    LOGGER.warning("Make sure the package is correctly installed")
```

And potentially set it to 0.0.0 for example when it is None.

**Comment by arnaudsjs** [comment]
It is quite ugly in my opinion, but I don't see an alternative. I will update the code.

**Review by sanderr — APPROVED** [review]
I agree it's not pretty but I haven't got any better suggestions either.

**Review by andraskvr — APPROVED** [review]

**Pull request merged**
