### PR TITLE
Issue/add changelog to documentation

### PR DESCRIPTION
**Pull request by arnaudsjs**
# Description

* Fix changelog format for the last two releases.
* Add changelog section to the documentation pages
* Enable markdown on the documentation

Note: Copying the `CHANGELOG.md` file into the docs directory will be the responsibility of the documentation build tool.

Part of inmanta/irt#417

# Self Check:

- [x] Attached issue to pull request
- [x] Changelog entry
- [ ] ~~Type annotations are present~~
- [ ] ~~Code is clear and sufficiently documented~~
- [ ] ~~No (preventable) type errors (check using make mypy or make mypy-diff)~~
- [ ] ~~Sufficient test cases (reproduces the bug/tests the requested feature)~~
- [ ] ~~Correct, in line with design~~
- [ ] ~~End user documentation is included or an issue is created for end-user documentation~~

# Reviewer Checklist:

- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Code is clear and sufficiently documented
- [ ] Correct, in line with design

### CODE REVIEW

**Review by sanderr — APPROVED** [review]
The docs part will be merged to iso4 (I believe iso3 will be built using the legacy docs build)?

**Comment by arnaudsjs** [comment]
Could you elaborate? I don't understand what you are saying.

**Comment by arnaudsjs** [comment]
ISO3 is built using the new docs build tool.

**Review by wouterdb — APPROVED** [review]

**Comment by wouterdb** [comment]
shouldn't there be a changelog.yml for mergetool?

**Comment by arnaudsjs** [comment]
> shouldn't there be a changelog.yml for mergetool?

True. I will add one.

**Pull request closed without merging**
