### PR TITLE
Install openapi dependencies from constraint file

### PR DESCRIPTION
**Pull request by arnaudsjs**
# Description

Install the `pytest-inmanta-extensions` via the `requirements.dev.txt` file as such that version constraints are taken into account.

### CODE REVIEW

**Review by sanderr — APPROVED** [review]
Do you make sure this gets cherry-picked to the appropriate places?

**Comment by arnaudsjs** [comment]
> Do you make sure this gets cherry-picked to the appropriate places?

Yes.

**Comment by arnaudsjs** [comment]
@sanderr I accidentally merged this one in without approval.

**Comment by sanderr** [comment]
I'd missed the request. Consider it approved.

**Pull request merged**
